scss_files: 'scss/**/'
exclude:
  - 'scss/Bootstrap/**'
  - 'scss/images/**'
  - 'scss/fonts/**'
  - 'scss/compass/**'
  - 'scss/animation/**'
  - 'scss/FontAwesome/**'
linters:
  ImportPath:
    enabled: false
  Indentation:
    width: 4
  PropertySortOrder:
    enabled: false
  FinalNewline:
    enabled: false
  StringQuotes:
    style: double_quotes
